sudo: required

services:
  - docker

before_install:
  - docker build -t franciscoserrano/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true franciscoserrano/react-test npm test

after_success:
  - docker build -t franciscoserrano/multi-client ./client
  - docker build -t franciscoserrano/multi-nginx ./nginx
  - docker build -t franciscoserrano/multi-server ./server
  - docker build -t franciscoserrano/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push franciscoserrano/multi-client
  - docker push franciscoserrano/multi-nginx
  - docker push franciscoserrano/multi-server
  - docker push franciscoserrano/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-2
  bucket_name: elasticbeanstalk-us-east-2-050422725413
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id: $AWS_SECRET_KEY